### ISSUE TITLE
[汇总] 降低问题排查成本, 降低整体复杂度

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#405]
## 现状

调用:
- SaaS调用 API 
- ESB/APIGateway调用 API
- API 数据同步模块
    - 调用LDAP
    - 调用 MAD
    - 调用 HTTP API 
- API 的auth模块(auth失败的场景)
- SaaS 的登录校验模块(登录无限跳转的场景)
- API 本身的校验报错信息

重点模块:
- bkuser_core/enhanced_account
- bkuser_core/esb_sdk
- bkuser_core/categories/plugins

TODO: 收集其他用户返回的错误堆栈信息

## 日志

已经处理了:

- [x] SaaS 调用后台没有详细的报错信息 + 打印双份日志问题 #357  #290 
- [x] 自定义exception缺失详情 #286
- [x] 通用日志打印优化, 详情+打印方式 #284 
- [x] 自定义登录打印详细日志 #309
- [x] #403  #408
- [x] #406 #409
- [x] 日志中存在敏感信息(后台不可用的时候会打印到日志文件中) #415
- [x] #296  #419
- [x] 初始化数据报错没有上下文, 难以定位 #422 
 

还需要确定的点:

- [ ] debug日志是否对问题排查有帮助?
- [ ] info日志是否包含足够多的过程信息?
- [ ] error日志是否都有上下文(重点排查log.exception)
- [ ] 是否足够方便检索(目前全部放stdout)
- [ ] 切换成文件, 是否足够细(需要确认是否支持v3的日志约定)
- [x] #360
- [ ] #407
- [ ] #374 
- [x] #358 

## 防御性处理

- [x] HTTP API 数据源校验  #390 #400 

## celery定时/异步

- [x] #402  #419
- [x] #404  #411

## metrics

?

## 文档

- [x] LDAP/MAD数据同步问题 FAQ汇总
- [ ] HTTP 数据源插件文档同步修改

## 其他

- [x] HTTP API数据同步部门记录了extra.code, 而profile没有记录(排查问题有困难) #420
- [x] 支持sentry #306 
- [x] user_settings目前允许插入重复的配置 #423 #425

**Comment by wklken** [comment]
修修补补加日志, 并没有真正解决问题, 降低问题排查的成本, 但是没有降低复杂度

-------

本质上, 应该分析几个点, 从根本上减少概念/封装, 降低复杂度
- saas通过sdk调用后台接口
- 后台接口提供了`过于通用`的查询能力, 导致viewset层过于复杂(重点: category/profile)
- 目录同步 plugins 机制(概念过多, 嵌套层级过深, 重点: 简化逻辑/减少封装)

**Comment by wklken** [comment]
- SaaS 逻辑已抹除, 重构到API的 api/v1/web
- SDK已抹除
- 解耦了 Open API 和 SaaS API
